services:
  bedrock-ai-agent-for-email:
    build: .
    container_name: bedrock-ai-agent-for-email
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py
    stdin_open: true
    tty: true
